### ISSUE TITLE
一个关于关联epub文件的小问题！A small question about associating epub files!

### ISSUE THREAD

**Issue by sr79368142** [btpf/Alexandria#10]
你好，可以告诉我怎么把程序关联为epub的默认阅读器，还有就是程序是不支持电脑上已经安装好的字体吗？只能用软件下载的字体？？？
--------------------------------------------------------------
Hello, can you tell me how to associate the program as the default reader for epub, and does the program not support the fonts already installed on the computer?Fonts that can only be downloaded by software?？？

**Comment by btpf** [comment]
I currently have not implemented file associations, though I can investigate this for the 1.0 release.

I also want system fonts, but I may never implement this because they will be impossible to sync and it's difficult to retrieve installed fonts across platforms. 
However, I intend to add the ability to install your own TTF font files in the future.

**Comment by sr79368142** [comment]
好的！非常感谢您的解答，祝您开发顺利，好运日日眷顾！😊
Ok!Thank you very much for your answer, I wish you a smooth development and good luck every day! 😊

**Comment by btpf** [comment]
Hi @sr79368142 , I thought I would update you here. 
In the latest version I decided to add system fonts just as you originally requested. The implementation is a quick and temporary one, but hopefully it will make your experience better.

Additionally, If you right click -> open -> Choose another app, you can set Alexandria to be the default application in this update.
![image](https://github.com/btpf/Alexandria/assets/61168382/d8008ed2-e7e6-4c92-ab26-c02927c74883)
When I upgrade this project to Tauri V2 in the coming months, I will be able set the associations in the installer hopefully.

You can get the latest release here: https://github.com/btpf/Alexandria/releases/tag/v0.11.0

Enjoy!
