### ISSUE TITLE
FB2 issues

### ISSUE THREAD

**Issue by johnfactotum** [btpf/Alexandria#14]
Since Alexandria is using Foliate's FB2 code, you should know that it has quite a few bugs:

- https://github.com/johnfactotum/foliate/issues/935.
- https://github.com/johnfactotum/foliate/issues/972
- https://github.com/johnfactotum/foliate/issues/1063

There's a patch in the comments for the first issue, and the second one should be straightforward to fix. I haven't investigated the last one, though.

**Comment by btpf** [comment]
I will use your first fix since it is complete.
But as you know, there are many issues related to EpubJS. I do not find investment toward related bugfixes worthwhile as Alexandria will eventually be switching to your much cleaner Foliate-js in the future. 

On a personal note though, thanks so much for your hard work. Without you, this project would not exist.
