### ISSUE TITLE
Titles not showing correctly

### ISSUE THREAD

**Issue by mindfulnessbergamo** [btpf/Alexandria#50]
Alexandria 0.12.0 on Windows 10. Titles do not show correctly (please see https://prnt.sc/YNJYcvKQtyIu). All other e-readers I tested my e-book on show titles correctly (Books app on iPhone/iPad, Foliate on Linux, Sigil and Calibre on Windows, Kindle Previewer 3 on Windows). My e-book validates on epubcheck ver 5.1.0 (EPUB 3.3).

**Comment by btpf** [comment]
The cause of this is not the rendering engine, but rather the way Alexandria specifically handles custom themes.

https://github.com/btpf/Alexandria/blob/main/src/store/slices/bookState.ts#L51-L98

Currently Alexandria sets a default line height of 100% on the body by default. Since the body font-size is smaller than the header font-size, the computed line-height is passed down. This is what causes the text overlap.

These two links describe the likely cause well:
- https://stackoverflow.com/a/12304722
- https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#prefer_unitless_numbers_for_line-height_values

I think as a solution I can set the line-height to use unitless numbers, and maybe have an option where the line-height override is disabled completely as a default.

I can look into these solutions for the next release. Thank you for testing.
