### ISSUE TITLE
AppImage issue with GLIBCXX_3.4.32

### ISSUE THREAD

**Issue by edent** [btpf/Alexandria#7]
Tried running the AppImage on Pop_OS (Ubuntu 22.04) and got this error:
```
alexandria: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /tmp/.mount_alexanFjr52b/usr/lib/libwebkit2gtk-4.0.so.37)
alexandria: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_alexanFjr52b/usr/lib/libsystemd.so.0)
alexandria: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_alexanFjr52b/usr/lib/libxml2.so.2)
alexandria: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /tmp/.mount_alexanFjr52b/usr/lib/libmount.so.1)
alexandria: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_alexanFjr52b/usr/lib/libmount.so.1)
alexandria: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_alexanFjr52b/usr/lib/libdw.so.1)
alexandria: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /tmp/.mount_alexanFjr52b/usr/lib/libXdmcp.so.6)
alexandria: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_alexanFjr52b/usr/lib/libblkid.so.1)
alexandria: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_alexanFjr52b/usr/lib/libelf.so.1)
alexandria: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_alexanFjr52b/usr/lib/libudev.so.1)
```

**Comment by jothi-prasath** [comment]
Same issue
Debian 12 Stable
![image](https://github.com/btpf/Alexandria/assets/64248628/a3442c98-ac45-4240-9fe7-af8f4a3f2473)

**Comment by btpf** [comment]
Hi, I have rebuilt the latest release on Debian 12. Please let me know if the issue is still present. Thanks!

https://github.com/btpf/Alexandria/releases/tag/0.9.1

**Comment by jothi-prasath** [comment]
the new 0.9.1 appimage works for me no error [Debian 12 Stable]

![image](https://github.com/btpf/Alexandria/assets/64248628/b97ad068-dba3-4534-88be-fb9a5051651b)

**Comment by btpf** [comment]
Hi @edent , I rebuilt again with Ubuntu 18 and tested on popOS myself. Can you confirm that it is working?
Thanks!

https://github.com/btpf/Alexandria/releases/tag/0.9.1

**Comment by btpf** [comment]
So I am able to replicate the issue with the floating bar, but none of the VM's I set up are getting this font issue. I will have to make some code changes for this fix,so ill get back to you when it's ready.

Here are some notes for myself and a summary of the current issue. 
If anybody has insight additional insight, please let me know.

Tauri Guide: https://tauri.app/v1/guides/building/linux/

I originally thought that Debian 12 Stable would be using the oldest version of glibc, But it turns out that the current version of Pop_OS, Based on Ubuntu, actually has the older glibc.
While Debian 12 builds were flawless for where glibc > 2.38, Pop OS was using 2.35. 
When I rebuilt with Ubuntu 18.04 (glibc 2.27), as the Tauri docs suggest, the resulting AppImage had some strange behavior.
Firstly, the build runs on Ubuntu 18.04 without any errors. It will also open on all platforms, but there are now errors
Arch:
```
Gtk-Message: 15:12:29.717: Failed to load module "xapp-gtk3-module"
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so

Gtk-Message: 15:12:30.153: Failed to load module "xapp-gtk3-module"

/usr/lib/libproxy/libpxbackend-1.0.so: undefined symbol: g_strv_builder_unref
Failed to load module: /usr/lib/gio/modules/libgiolibproxy.so
/usr/lib/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiognomeproxy.so
/tmp/.mount_alexannP8Dyf/usr/lib/libgnutls.so.30: version `GNUTLS_3_6_3' not found (required by /usr/lib/gio/modules/libgiognutls.so)
Failed to load module: /usr/lib/gio/modules/libgiognutls.so
```
Pop_OS
```
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
(WebKitWebProcess:215333): Gtk-WARNING **: 10:20:16.539: Theme parsing error: gtk-dark.css:1427:23: 'font-feature-settings' is not a valid property name
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
```
I'm not sure the cause of these errors, But the app will open and function with only one new issue.

HTML and CSS seem to be behaving differently. It seems there is an issue with the font, But for the floating menu, A CSS Change would fix the problem.

Instead of `align-items: flex-end`, I wrote `align-items: end`. Using `end` as the value of `align-items` for a flexbox is not correct, But it's interesting that this didn't show on windows or even the debian builds. Especially since i ran on both debian and ubuntu 
`sudo apt install libwebkit2gtk-4.0-dev`. Doesn't this rule out a different version of webkit being the cause? Could it be that these css inconsistencies are related to the new errors?

**Comment by btpf** [comment]
Please give https://github.com/btpf/Alexandria/releases/tag/0.9.2 a try and tell me if there are any issues besides the errors in console. 
Thanks for being patient and helping.
